version: "3"
services:
  jupyter-server:
    build: ./build
    command:
      - jupyterhub
    volumes:
      - ./notebook-data:/home/sirily11
      - ./config:/srv/jupyterhub
    ports:
      - 8083:8083
    environment:
      - JUPYTER_ENABLE_LAB=yes
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "production_status"
        env: "os"
